### ISSUE TITLE
Entrypoint issue on Vite 

### ISSUE THREAD

**Issue by Majestic9169** [arav-ind/react-svgmap-india#3]
**Error Message:**
> [plugin:vite:import-analysis] Failed to resolve entry for package "react-svgmap-india". The package may have incorrect main/module/exports specified in its package.json.

/home/subzcuber/Public/git-repos/energy-conslut-ui/src/App.tsx:3:21

```js
18 |  import { useState } from "react";
19 |  import "./App.css";
20 |  import IndiaMap from "react-svgmap-india";
   |                        ^
21 |  function App() {
22 |    _s();
```

**Stack Trace:**
```
    at packageEntryFailure (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:16287:15)
    at resolvePackageEntry (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:16284:3)
    at tryNodeResolve (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:16149:18)
    at ResolveIdContext.resolveId (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:15934:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EnvironmentPluginContainer.resolveId (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:46929:22)
    at async TransformPluginContext.resolve (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:47089:15)
    at async normalizeUrl (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:45419:26)
    at async file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:45550:39
    at async Promise.all (index 5)
    at async TransformPluginContext.transform (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:45477:7)
    at async EnvironmentPluginContainer.transform (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:47009:18)
    at async loadAndTransform (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:40848:27)
    at async viteTransformMiddleware (file:///home/subzcuber/Public/git-repos/energy-conslut-ui/node_modules/.pnpm/vite@6.0.2/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:42292:24
```

**Environment Information:**
- Node.js Version: v23.1.0
- React Version: 18.3.1
- Operating System: Arch Linux
- Browser: Mozilla Firefox 133.0

**Code Snippet:**
```javascript
import { useState } from 'react'
import './App.css'
import IndiaMap from 'react-svgmap-india'

function App() {
  const [state, setState] = useState("")

  return (
    <>
      <div>
        <h1>{state}</h1>
        <IndiaMap
          size='500px'
          mapColor='white'
          strokeColor='#4f4f4f'
          strokeWidth='1'
          hoverColor='#48d8f5'
          onClick={(e) => setState(e)}
        />
      </div>
    </>
  )
}
```

**Comment by arav-ind** [comment]
Hii! Thanks for reporting. I have fixed and published v2.1.0.
